artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/raw/churn_data.csv

  database:
    database_name: churn_db
    table_name: customer_churn